Feature/create project script
neo-empresarial/clockify-integration pull request #53
Opened 2019-11-18 18:05 UTC by ribeirojose

Solve #47

2019-11-20 13:15 UTC, lukasab commented on services/create_project.py
> +        "n": "#FF9800",
Not sure if this changes something, but this is how it is in clockify:

```suggestion
        "n": "#ff9800",
```

2019-11-20 13:16 UTC, lukasab commented on services/create_project.py
> +        "c": "#8BC34A",
Same here:

```suggestion
        "c": "#8bc34a",
```

2019-11-20 13:17 UTC, lukasab commented on services/create_project.py
> +        "tasks": [{"name": x.name} for x in default_activities.all()],
```suggestion
        "tasks": [{"name": activity.name} for activity in default_activities.all()],
```

2019-11-20 13:19 UTC, lukasab commented on services/create_project.py
> +# TODO: implement clients in our DB
Just so I know, what is this?

2019-11-20 13:21 UTC, lukasab commented on services/create_project.py
> +    new_proj = Project.create(name=project_name, clockify_id=proj_clockify_id)
Nice! I would forget to create the project in our DB.

2019-11-20 13:22 UTC, lukasab commented on services/create_project.py
> +    new_proj.activities().sync(default_activities.map(lambda x: x.id).all())
I'm not sure what this does, but:

```suggestion
    new_proj.activities().sync(default_activities.map(lambda activity: activity.id).all())
```

2019-11-20 13:23 UTC, lukasab requested changes
Well done. You used click :blush:!!

2019-11-20 13:25 UTC, lukasab commented on services/create_project.py
> +        "color": colors[project_name.lower()[0]],
I think it's missing an exception for when the project doesn't start with does letters.

2019-11-20 13:36 UTC, lukasab commented
Added this to our [wiki](http://wiki.neo.ufsc.br/index.php?title=Uso_do_Clockify).

2019-11-22 21:01 UTC, lukasab commented
I could not run the code because it needs the _template_ project. How are you thinking about creating this project(The one with all default activities)?

2019-11-24 13:02 UTC, ribeirojose commented
> I could not run the code because it needs the _template_ project. How are you thinking about creating this project(The one with all default activities)?

We should probably add this with the migrations, right? We should probably have a seed file to populate the db with this sort of thing. What do you think?

2019-11-24 13:08 UTC, ribeirojose commented on services/create_project.py
> +    proj_response = requests.post(
This should be a `Project` method, so you don't have to star import everything.

2019-11-25 12:39 UTC, lukasab commented
> > I could not run the code because it needs the _template_ project. How are you thinking about creating this project(The one with all default activities)?
> 
> We should probably add this with the migrations, right? We should probably have a seed file to populate the db with this sort of thing. What do you think @lukasab ?

I think it does make a lot of sense adding this to the project/activities migration file. What do you mean by a seed file?

2019-11-25 12:46 UTC, lukasab requested changes
We can approve this after we solve the template activities issue.

2019-11-25 12:46 UTC, lukasab commented on services/create_project.py
> +    except:
Just to be specific about what exception you're trying to catch.

```suggestion
    except ValueError:
```

2019-11-25 12:46 UTC, lukasab commented on services/create_project.py
> +    if not valid_project_name(name, colors.keys()):
nice!

2019-11-25 13:40 UTC, ribeirojose commented
> > > I could not run the code because it needs the _template_ project. How are you thinking about creating this project(The one with all default activities)?
> > 
> > 
> > We should probably add this with the migrations, right? We should probably have a seed file to populate the db with this sort of thing. What do you think @lukasab ?
> 
> I think it does make a lot of sense adding this to the project/activities migration file. What do you mean by a seed file?

Something around these lines:

```python
from orator.seeds import Seeder
from functools import reduce

class ProjectTableSeeder(Seeder):

    def run(self):
        """
        Run the database seeds.
        """

        # Here you could just use random string generators
        # rather than hardcoded values
        self.db.table('project').insert({
           'id': 0,
            'name': 'template',
        }),
        default_proj_activity_ids = [ ... ]
        project_activity_content = reduce(
                lambda acc, id_: [*acc, {
                        'project_id': 0,
                        'activity_id': id_
                        }],
                        default_proj_activity_ids,
                        []) 
        self.db.table('project_activity').insert()
```

2019-12-10 16:01 UTC, lukasab commented
> > > > I could not run the code because it needs the _template_ project. How are you thinking about creating this project(The one with all default activities)?
> > > 
> > > 
> > > We should probably add this with the migrations, right? We should probably have a seed file to populate the db with this sort of thing. What do you think @lukasab ?
> > 
> > 
> > I think it does make a lot of sense adding this to the project/activities migration file. What do you mean by a seed file?
> 
> Something around these lines:
> 
> ```python
> from orator.seeds import Seeder
> from functools import reduce
> 
> class ProjectTableSeeder(Seeder):
> 
>     def run(self):
>         """
>         Run the database seeds.
>         """
> 
>         self.db.table('project').insert({
>            'id': 0,
>             'name': 'template',
>         }),
>         default_activity_ids = [ ... ]
>         default_vals_project_activity = reduce(
>                 lambda acc, id_: [*acc, {
>                         'project_id': 0,
>                         'activity_id': id_
>                         }],
>                         default_activity_ids,
>                         []) 
>         self.db.table('project_activity').insert(default_vals_project_activity)
> ```

Have you implemented this?

2020-08-17 20:49 UTC, ribeirojose commented
Closing due to no further activity.

2020-08-17 20:49 UTC, closed without merging